### GET request to example server
GET http://localhost:8080/foods
###

### POST Food

POST localhost:8080/foods
Content-Type: application/json

{
  "name": "Meat",
  "price": 12.30
}

###


### CREATE USER

POST localhost:8080/users
Content-Type: application/json

{
  "username": "m.gzegozevskis@gmail.com",
  "password": "LabasAsKrabas"
}

###