// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteExpiredSessions(ctx context.Context, expiresAt pgtype.Timestamp) error
	DeleteSession(ctx context.Context, sessionToken string) error
	DeleteUserSessions(ctx context.Context, userID int32) error
	GetAllFood(ctx context.Context) ([]Food, error)
	GetSessionByToken(ctx context.Context, arg GetSessionByTokenParams) (GetSessionByTokenRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, id int32) (GetUserByIdRow, error)
	GetUserSessions(ctx context.Context, arg GetUserSessionsParams) ([]Session, error)
	InsertFood(ctx context.Context, arg InsertFoodParams) (Food, error)
}

var _ Querier = (*Queries)(nil)
